优化了探虚变实，鱼死网破的ai
CuteReimu/TheMessage pull request #180
Opened 2024-03-20 11:28 UTC by planetmiku

2024-03-20 11:44 UTC, CuteReimu requested changes

2024-03-20 11:44 UTC, CuteReimu commented on src/main/kotlin/skill/YuSiWangPo.kt
> +                    .run{if (e.whoseTurn.identity !=Black) filter{it!!.identity !=Black}.ifEmpty{ this} else this }
1. 格式化一下。
2. 为什么要改成鱼死网破会对1牌的目标使用？

2024-03-20 11:44 UTC, CuteReimu commented on src/main/kotlin/phase/MainPhaseIdle.kt
> +) : ProcessFsm() {
注释不是这样写的，应该是这样：
```kotlin
/**
 * 出牌阶段空闲时点
 *
 * @param whoseTurn 当前回合的玩家
 */
data class MainPhaseIdle(override val whoseTurn: Player) : ProcessFsm() {
```

2024-03-21 02:47 UTC, CuteReimu approved these changes

2024-03-21 03:15 UTC, planetmiku reviewed
优化了探虚变实，鱼死网破的ai

2024-03-21 03:20 UTC, merged